version: '3'
services:
  api:
    build: .
    container_name: music-info-api
    ports:
      - "8080:8080"
    env_file:
      - config/dbconf.env
      # - /app/config/dbconf.env 

    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: music-info-db
    restart: always
    env_file:
      - config/dbconf.env
      # - /app/config/dbconf.env 
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
