/*
 * Music Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

type SongDetail struct {
	SeqNum string `json:"SeqNum,omitempty"`

	ID int32 `json:"ID,omitempty"`

	Title string `json:"Title,omitempty"`

	ReleaseDate string `json:"ReleaseDate,omitempty"`

	Artist string `json:"Artist,omitempty"`

	Text string `json:"Text,omitempty"`

	Lyrics string `json:"Lyrics,omitempty"`

	Link string `json:"Link,omitempty"`
}
