/*
 * Music Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

type NewSongRequest struct {
	Group string `json:"group,omitempty"`

	Song string `json:"song,omitempty"`
}
