/*
 * Music Service API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type UpdateSongRequest struct {

	Text string `json:"Text,omitempty"`

	Artist string `json:"Artist,omitempty"`

	ReleaseDate string `json:"ReleaseDate,omitempty"`

	Title string `json:"Title,omitempty"`
}
