/*
 * Music Service API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package server

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"SongsGet",
		strings.ToUpper("Get"),
		"/v1/songs",
		SongsGet,
	},

	Route{
		"SongsIdDelete",
		strings.ToUpper("Delete"),
		"/v1/songs/{id}",
		SongsIdDelete,
	},

	Route{
		"SongsIdGet",
		strings.ToUpper("Get"),
		"/v1/songs/{id}",
		SongsIdGet,
	},

	Route{
		"SongsIdLyricsGet",
		strings.ToUpper("Get"),
		"/v1/songs/{id}/lyrics",
		SongsIdLyricsGet,
	},

	Route{
		"SongsIdPut",
		strings.ToUpper("Put"),
		"/v1/songs/{id}",
		SongsIdPut,
	},

	Route{
		"SongsPost",
		strings.ToUpper("Post"),
		"/v1/songs",
		SongsPost,
	},

	Route{
		"SongsSearchGet",
		strings.ToUpper("Get"),
		"/v1/songs/search",
		SongsSearchGet,
	},
}
